// A DTO (Data Transfer Object) class is nothing but a pojo (plain old java object) class that follows some rules.
//These rules create it a DTO class.
package com.example.VotingProject.in.voter.dto;


import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.Size;
import lombok.Data;

@Data
public class EmpUpdateDTO {
    //Creating instance variables that are needed to update an employee
    @Size(min = 1, message = "Employee name must be atleast 3 characters long || cannot be empty || Reply from UpdateEmpDTO")
    private String ename;
    @Min(value = 10000, message = "Employee salary must be atleast ₹10000 || Reply from UpdateEmpDTO")
    private Double sal;
}
//we don't need id as it will be automatically taken from the path variable in the controller method.
//No-args constructor, getters and setters will be automatically generated by Lombok's @Data
//This DTO will be used in the controller method to receive the update request data
//This DTO will be mapped to the Emp entity in the service layer for updating the employee details
